### ISSUE TITLE
Spiel stürzt bei setzen von Feld A7 ab

### ISSUE THREAD

**Issue by thomsmits** [lucaSchilling/OOThello#7]
Spieler: Noob2000
Farbe: Schwarz
Spielen gegen Computer
Größe 6
Starke KI
Schwarz beginnt
Setzen: A7
Exception!

```

Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at oothello.Spieler.setzPhaseZug(Spieler.java:101)
	at oothello.Spieler.setzStein(Spieler.java:32)
	at oothello.Spiel.zug(Spiel.java:222)
	at oothello.Spiel.starteSpiel(Spiel.java:155)
	at oothello.Eingaben.einzelspielerEingabe(Eingaben.java:176)
	at oothello.Eingaben.spielenEingabe(Eingaben.java:89)
	at oothello.Eingaben.menueEingaben(Eingaben.java:44)
	at oothello.Spiel.menue(Spiel.java:91)
	at oothello.Spiel.main(Spiel.java:25)
```

**Comment by lucaSchilling** [comment]
fixed

**Comment by thomsmits** [comment]
Bei starker KI immer noch crash.

**Comment by thomsmits** [comment]
Sorry, mein Fehler. Habe nicht refreshed.
